# Generated by Django 5.0.6 on 2024-06-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchaptercompletion',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
