# Generated by Django 5.0.6 on 2024-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_studentchaptercompletion_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='color',
            field=models.CharField(choices=[('blue', '#0284c7'), ('green', '#0bb801'), ('yellow', '#ffea00'), ('red', '#df0000'), ('purple', '#5900df'), ('gray', '#616161'), ('pink', '#e300c5'), ('orange', '#ffa500')], default='blue', max_length=20),
        ),
    ]
