# Generated by Django 5.0.6 on 2024-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_alter_student_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='color',
            field=models.CharField(choices=[('#0284c7', 'blue'), ('#0bb801', 'green'), ('#ffea00', 'yellow'), ('#df0000', 'red'), ('#5900df', 'purple'), ('#616161', 'gray'), ('#e300c5', 'pink'), ('#ffa500', 'orange')], default='blue', max_length=20),
        ),
    ]
