# Generated by Django 5.0.6 on 2024-07-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_chapter_description_subject_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
