# Generated by Django 5.0.6 on 2024-07-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='learn/subject/thumbnails'),
        ),
    ]
