# Generated by Django 5.0.6 on 2024-07-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_subject_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='learn/subject/thumbnails'),
            preserve_default=False,
        ),
    ]
