# Generated by Django 5.0.6 on 2024-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_alter_subject_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='learn/chapter/thumbnails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='learn/topic/thumbnails'),
            preserve_default=False,
        ),
    ]
