# Generated by Django 5.0.6 on 2024-07-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_chapter_content_chapter_review_topic_review_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='ChapterQuiz',
        ),
        migrations.RenameModel(
            old_name='QuizResult',
            new_name='ChapterQuizResult',
        ),
    ]
