# Generated by Django 5.0.6 on 2024-07-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_rename_question_chapterquiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('mark', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chapterquiz',
            options={'verbose_name_plural': 'Chapter Quizzes'},
        ),
        migrations.RenameField(
            model_name='chapterquiz',
            old_name='question_text',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.chapterchoice'),
        ),
        migrations.CreateModel(
            name='ChapterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learn.chapterquiz')),
            ],
        ),
        migrations.AddField(
            model_name='chapterchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learn.chapterquestion'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
