# Generated by Django 5.0.6 on 2024-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_remove_studentanswer_quiz_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquiz',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
