# Generated by Django 5.0.6 on 2024-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_chapterquiz_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquiz',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
