# Generated by Django 5.0.6 on 2024-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_chapterquiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquiz',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapterquiz',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(300, '5 min'), (420, '7 min'), (600, '10 min'), (780, '13 min'), (900, '15 min'), (1020, '17 min'), (1200, '20 min')], default='5 min', null=True),
        ),
    ]
